version: '3.5'
services:
  apigateway:
    image: nginx:latest
    container_name: apigateway
    ports:
      - "80:80"
    volumes:
      - ../api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
