version: '3.5'
services:
  comicservice:
    image: comicservice
    container_name: comicservice
    ports: 
      - 5100:5100
    restart: unless-stopped
    depends_on:
      - comicservice-db
    networks:
      - comicservice-network
  comicservice-db:
    image: postgres
    container_name: comicservice-db
    ports:
      - 5441:5432
    environment:
      - POSTGRES_PASSWORD=Qwe123!
    volumes:
      - comicservice_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - comicservice-network

networks:
  comicservice-network:
    name: comicservice-network
    driver: bridge

volumes:
  comicservice_db_data: