version: '3.5'
services:
  comiczone-userservice:
    image: comiczone-userservice
    container_name: comiczone-userservice
    ports: 
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - user-service-network
  db:
    image: postgres
    container_name: db
    ports:
      - 5440:5432
    environment:
      - POSTGRES_PASSWORD=Qwe123!
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - user-service-network

networks:
  user-service-network:
    name: user-service-network
    driver: bridge

volumes:
  db_data: